[CmdletBinding()]
param(
  [string] $StateRoot = (Join-Path $env:LOCALAPPDATA 'HermesMcp'), [switch] $Once, [int] $RetrySeconds = 15,
  [string] $HermesRoot = (Join-Path $env:LOCALAPPDATA 'hermes'), [string] $NodePath = 'node.exe', [string] $AdapterEntryPath = '',
  [ValidateRange(1,120)][int] $TunnelTimeoutSeconds = 20, [ValidateRange(1,120)][int] $TunnelReadyWaitSeconds = 15, [ValidateRange(10,5000)][int] $HealthPollMilliseconds = 250, [ValidateRange(1,120)][int] $AdapterReadyWaitSeconds = 10, [ValidateRange(0,100000)][int] $MaxCycles = 0
)
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($AdapterEntryPath)) { $AdapterEntryPath = Join-Path (Split-Path $PSScriptRoot -Parent) 'dist\index.js' }
function Assert-RuntimeConfig($c) { if ([string]$c.tunnel_id -notmatch '^tunnel_[A-Za-z0-9_-]{6,}$') { throw 'Invalid tunnel ID.' }; foreach ($n in @('alias','profile')) { if ([string]$c.$n -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$') { throw "Invalid $n." } }; $p=[string]$c.tunnel_client_path; if ([string]::IsNullOrWhiteSpace($p) -or -not [IO.Path]::IsPathRooted($p) -or $p.IndexOfAny([char[]]"`"`r`n") -ge 0 -or [IO.Path]::GetExtension($p) -notin @('.exe','.ps1')) { throw 'Invalid tunnel client path.' }; foreach ($n in @('adapter_url','gateway_url')) { $u=[uri]$c.$n; $ip=$null; if ($u.Scheme -notin @('http','https') -or -not [Net.IPAddress]::TryParse($u.Host,[ref]$ip) -or -not [Net.IPAddress]::IsLoopback($ip) -or -not [string]::IsNullOrEmpty($u.UserInfo) -or $u.AbsolutePath -ne '/' -or -not [string]::IsNullOrEmpty($u.Query) -or -not [string]::IsNullOrEmpty($u.Fragment)) { throw "Invalid $n." } } }
function Test-Health([string]$Url,[string]$Wanted) { try { $r=Invoke-WebRequest -UseBasicParsing -Uri $Url -MaximumRedirection 0 -TimeoutSec 2; return $r.StatusCode -eq 200 -and (($r.Content|ConvertFrom-Json).status -eq $Wanted) } catch { return $false } }
function Wait-Health([string]$Url,[string]$Wanted,[int]$Seconds) { $until=[DateTime]::UtcNow.AddSeconds($Seconds); do { if(Test-Health $Url $Wanted){return $true}; Start-Sleep -Milliseconds $HealthPollMilliseconds } while([DateTime]::UtcNow -lt $until); return $false }
function Get-MarkerPath([string]$name) { $dir=Join-Path $StateRoot 'processes'; [IO.Directory]::CreateDirectory($dir)|Out-Null; return (Join-Path $dir "$name.json") }
function Test-OwnedProcess([string]$name) { try { $m=Get-Content -LiteralPath (Get-MarkerPath $name) -Raw|ConvertFrom-Json; $p=Get-Process -Id ([int]$m.pid) -ErrorAction Stop; if($p.StartTime.ToUniversalTime().Ticks -ne [Int64]$m.start_time_ticks){return $false}; if(-not [string]::IsNullOrEmpty([string]$m.executable_path) -and $p.MainModule.FileName -ne [string]$m.executable_path){return $false}; return $true } catch { return $false } }
function Save-OwnedProcess([string]$name,$p) { $exe=''; try{$exe=$p.MainModule.FileName}catch{}; [ordered]@{pid=$p.Id;start_time_ticks=$p.StartTime.ToUniversalTime().Ticks;executable_path=$exe}|ConvertTo-Json -Compress|Set-Content -LiteralPath (Get-MarkerPath $name) -Encoding UTF8 }
function Invoke-Tunnel($c,[string]$runtimeKey) { $a="runtimes connect --alias `"$($c.alias)`" --tunnel-id `"$($c.tunnel_id)`" --runtime-api-key env:CONTROL_PLANE_API_KEY --mcp-server-url `"$($c.adapter_url)/mcp`" --profile `"$($c.profile)`" --profile-dir `"$(Join-Path $StateRoot 'tunnel-profiles')`" --json"; $i=[Diagnostics.ProcessStartInfo]::new(); $i.UseShellExecute=$false;$i.CreateNoWindow=$true;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true; if([IO.Path]::GetExtension([string]$c.tunnel_client_path) -ieq '.ps1'){$i.FileName='powershell.exe';$i.Arguments="-NoProfile -ExecutionPolicy Bypass -File `"$($c.tunnel_client_path)`" $a"}else{$i.FileName=$c.tunnel_client_path;$i.Arguments=$a};$i.Environment['CONTROL_PLANE_API_KEY']=$runtimeKey; $p=[Diagnostics.Process]::Start($i); try{$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit($TunnelTimeoutSeconds*1000)){try{$p.Kill()}catch{};$p.WaitForExit(2000)|Out-Null;return @{timed_out=$true;exit_code=$null}};$o.GetAwaiter().GetResult()|Out-Null;$e.GetAwaiter().GetResult()|Out-Null;return @{timed_out=$false;exit_code=$p.ExitCode}}finally{$p.Dispose()} }
function Get-SanitizedHealth { $output=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'Get-HermesMcpHealth.ps1') -StateRoot $StateRoot -TunnelTimeoutSeconds $TunnelTimeoutSeconds; $code=$LASTEXITCODE; if([string]::IsNullOrWhiteSpace(($output -join ''))){throw 'Health script returned no result.'}; return @{result=(($output -join '')|ConvertFrom-Json);exit_code=$code} }
function Wait-TunnelReady { $until=[DateTime]::UtcNow.AddSeconds($TunnelReadyWaitSeconds); do{$h=Get-SanitizedHealth;if($h.exit_code -eq 0){return $true};if(-not $h.result.gateway.reachable -or -not $h.result.adapter.healthy -or -not $h.result.adapter.ready){return $false};Start-Sleep -Milliseconds $HealthPollMilliseconds}while([DateTime]::UtcNow -lt $until);return $false }
function Invoke-Cycle {
  $c=Get-Content -LiteralPath (Join-Path $StateRoot 'config.json') -Raw|ConvertFrom-Json;Assert-RuntimeConfig $c;$g=([uri]$c.gateway_url).GetLeftPart([System.UriPartial]::Authority)+'/health';$ah=([uri]$c.adapter_url).GetLeftPart([System.UriPartial]::Authority)+'/healthz';$ar=([uri]$c.adapter_url).GetLeftPart([System.UriPartial]::Authority)+'/readyz'
  if(-not(Test-Health $g 'ok')){if(-not(Test-OwnedProcess 'gateway')){$exe=Join-Path $HermesRoot 'bin\hermes.exe';if(-not(Test-Path -LiteralPath $exe)){return $false};Save-OwnedProcess 'gateway' (Start-Process -FilePath $exe -ArgumentList @('gateway','run') -WindowStyle Hidden -PassThru)};if(-not(Wait-Health $g 'ok' $AdapterReadyWaitSeconds)){return $false}}
  if(-not(Test-Health $ah 'ok')){if(-not(Test-OwnedProcess 'adapter')){$line=Get-Content -LiteralPath (Join-Path $HermesRoot '.env')|Where-Object{$_ -match '^API_SERVER_KEY='}|Select-Object -First 1;$key=$line -replace '^API_SERVER_KEY=','';if($key.Length -lt 16){return $false};$i=[Diagnostics.ProcessStartInfo]::new($NodePath,"`"$AdapterEntryPath`"");$i.UseShellExecute=$false;$i.CreateNoWindow=$true;$i.Environment['HERMES_API_KEY']=$key;$i.Environment['HERMES_API_URL']=$c.gateway_url;$i.Environment['PORT']=([uri]$c.adapter_url).Port;Save-OwnedProcess 'adapter' ([Diagnostics.Process]::Start($i))};if(-not(Wait-Health $ah 'ok' $AdapterReadyWaitSeconds)){return $false}}
  if(-not(Wait-Health $ar 'ready' $AdapterReadyWaitSeconds)){return $false};$h=Get-SanitizedHealth;if($h.exit_code -eq 0){return $true};if($h.result.tunnel.process_running){return Wait-TunnelReady};$secure=(Get-Content -LiteralPath (Join-Path $StateRoot 'secrets\control-plane-api-key.dpapi') -Raw).Trim()|ConvertTo-SecureString;$ptr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure);try{$runtimeKey=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)};try{$connect=Invoke-Tunnel $c $runtimeKey}finally{Remove-Variable runtimeKey -ErrorAction SilentlyContinue};if($connect.timed_out){return $false};return Wait-TunnelReady
}
if($Once){try{$ready=Invoke-Cycle}catch{$ready=$false};[ordered]@{overall=if($ready){'ready'}else{'degraded'}}|ConvertTo-Json -Compress;if($ready){[Environment]::Exit(0)}else{[Environment]::Exit(2)}}
$cycles=0;while($MaxCycles -eq 0 -or $cycles -lt $MaxCycles){try{Invoke-Cycle|Out-Null}catch{};$cycles++;if($MaxCycles -eq 0 -or $cycles -lt $MaxCycles){Start-Sleep -Seconds ([Math]::Max(1,$RetrySeconds))}}
